version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /.*
  script: dreambox.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
